devices:
  - buzzer
  - front_light
  - left_light
  - beacon

buzzer:
  type: single_output_manager/SingleOutputManager
  namespace: robotnik_base_hw/set_digital_output
  output_number: 4

front_light:
  type: single_output_manager/SingleOutputManager
  namespace: robotnik_base_hw/set_digital_output
  output_number: 5

left_light:
  type: single_output_manager/SingleOutputManager
  namespace: robotnik_base_hw/set_digital_output
  output_number: 6

beacon:
  type: signal_single_output_manager/SignalSingleOutputManager
  namespace: robotnik_base_hw/set_digital_output
  output_number: 7
  signals:
    - id: "charging"
      enabled: false 